name: Auto Punch Card

on:
  schedule:
    # 工作日上午7:05执行（上班卡）
    - cron: '5 23 * * 0-4'
    # 工作日下午18:05执行（下班卡）
    - cron: '5 10 * * 1-5'
  workflow_dispatch: # 允许手动触发

jobs:
  punch:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      PUNCH_URL: ${{ secrets.PUNCH_URL }}
      PUNCH_TOKEN: ${{ secrets.PUNCH_TOKEN }}
      APP_VERSION_NUMBER: ${{ secrets.APP_VERSION_NUMBER }}
      FEISHU_BOT_WEBHOOK: ${{ secrets.FEISHU_BOT_WEBHOOK }}
      ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Check local time
      run: |
        date
        node -e "console.log('Node local time:', new Date().toString())"

    - name: Debug env presence
      run: |
        node -e "console.log('Has PUNCH_TOKEN:', !!process.env.PUNCH_TOKEN)"
        node -e "console.log('Has PUNCH_URL:', !!process.env.PUNCH_URL)"
        node -e "console.log('Has APP_VERSION_NUMBER:', !!process.env.APP_VERSION_NUMBER)"
        node -e "console.log('Has FEISHU_BOT_WEBHOOK:', !!process.env.FEISHU_BOT_WEBHOOK)"
        node -e "console.log('Has ZHIPU_API_KEY:', !!process.env.ZHIPU_API_KEY)"
    
    - name: Punch Card
      run: node index.js
